### ISSUE TITLE
Error when importing in SvelteKit: "SyntaxError: export declarations may only appear at top level of a module"

### ISSUE THREAD

**Issue by Mitcheljager** [RevenueCat/purchases-capacitor#184]
When importing this package via a regular import in SvelteKit I always get the same error, preventing my app from running at all. `SyntaxError: export declarations may only appear at top level of a module`

```swift
[vite] Error when evaluating SSR module /src/routes/+layout.svelte: failed to import "@revenuecat/purchases-capacitor"
|- /home/projects/sveltejs-kit-template-default-vkgyxe/node_modules/@revenuecat/purchases-typescript-internal-esm/dist/index.js:1
export * from './errors';
^^^^^^

SyntaxError: export declarations may only appear at top level of a module
    at internalCompileFunction (node:internal/vm:180:1006)
    at wrapSafe (node:internal/modules/cjs/loader:55:14103)
    at Module.prototype._compile (node:internal/modules/cjs/loader:55:14520)
    at Module._extensions[".js"] (node:internal/modules/cjs/loader:55:15550)
    at Module.prototype.load (node:internal/modules/cjs/loader:55:13457)
    at Module._load (node:internal/modules/cjs/loader:55:10535)
    at Module.prototype.require (node:internal/modules/cjs/loader:55:13775)
    at i (node:internal/modules/cjs/helpers:98:2198)
    at _0x96f9b1 (https://sveltejskittemplatedefaultvkgy-vgvr.w-corp.staticblitz.com/blitz.f7aa08df.js:352:197051)
    at  (/home/projects/sveltejs-kit-template-default-vkgyxe/node_modules/@revenuecat/purchases-capacitor/dist/plugin.cjs.js:6:45)
    at function (https://sveltejskittemplatedefaultvkgy-vgvr.w-corp.staticblitz.com/blitz.f7aa08df.js:352:197851)
    at Module.prototype._compile (node:internal/modules/cjs/loader:55:14871)
    at Module._extensions[".js"] (node:internal/modules/cjs/loader:55:15550)
    at Module.prototype.load (node:internal/modules/cjs/loader:55:13457)
    at Module._load (node:internal/modules/cjs/loader:55:10535)
    at  (node:internal/modules/esm/translators:189:2451)
    at _evaluate (https://sveltejskittemplatedefaultvkgy-vgvr.w-corp.staticblitz.com/blitz.f7aa08df.js:352:376371)
    at evaluate (https://sveltejskittemplatedefaultvkgy-vgvr.w-corp.staticblitz.com/blitz.f7aa08df.js:352:375441)
    at run (node:internal/modules/esm/module_job:181:2390)
 ```

This error can be overcome by importing the plugin async via `const { Purchases } = await import('@revenuecat/purchases-capacitor)`  

I set up a basic SvelteKit project which has basically nothing but SvelteKit and this package, which can be found here: https://stackblitz.com/edit/sveltejs-kit-template-default-vkgyxe?file=src%2Froutes%2F%2Blayout.svelte. Comment the import on line 5 to see it working as expected with an async import.

**Comment by Mitcheljager** [comment]
I realize now this is mentioned in this docs, so it seems this was my mistake

> There is no way to import RevenueCat into NodeJS, we don't make any such modules or sdks. The best option is to use our APIs directly using Node fetch. In our API docs you should use our JavaScript language to do so.
